# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actualBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookTitle', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='bookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='actualbook',
            name='bookCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchApp.bookCategory'),
        ),
    ]
