# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualbook',
            old_name='bookCategory',
            new_name='actualbookCategory',
        ),
        migrations.RenameField(
            model_name='actualbook',
            old_name='bookTitle',
            new_name='actualbookTitle',
        ),
    ]
