# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0002_auto_20160714_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualbook',
            name='actualbookTitle',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
