"""
    This is url file created by duplicating searchProject/url.py (i.e. it is not initially autogenerated)
    It is what "tells" Django of te existence of a page "render" created in view
    The line 'from django.contrib import admin' was removed as it does not apply
    The line 'from django.conf.urls import url' was left as it applies in this case

    Basically what the urlpatterns is doing is that it uses regex to match any character "after root"
    i.e. r'^$' then links it to method 'views.index' and renames it with the value in 'name'

    Note we imported the object views before calling its functions indexPage, SearchPage etc.
    r'^$' can be used here to match root page "www.google.com/"
        - nothing between ^ and $ means when we have an "empty string"

"""
from django.conf.urls import url
from searchApp import views

urlpatterns = [
    url(r'^$', views.indexPage, name='indexPage'),
    url(r'^searchPage/$', views.searchPage, name='searchPage'),
]
